---
title: "網路爬蟲練習RSelenium"
author: "Simon"
date: "2023-02-03"
output: html_document
---

```{r, include=FALSE}
rm(list = ls())
```

```{r, include=FALSE}
library(tidyverse)
library(rvest)
library(magrittr)
library(ggplot2)
library(stringr)
library(httr)
library(RSelenium)
library(RCurl)
library(netstat)
```

瀑布式網頁爬蟲網址：
https://github.com/CGUIM-BigDataAnalysis/BigDataCGUIM/blob/master/108/RSelenium_rvest.md

Selenium教學
https://www.youtube.com/watch?v=U1BrIPmhx10&ab_channel=SamerHijjazi

```{r}
remDr <- remoteDriver(browserName = "chrome")
remDr$open()
```

```{r}
#navigate to website
remDr$navigate("https://www.ebay.com/")

#finding elements
sports_objects <- remDr$findElement(using = c("link text"), "Sports")
sports_objects$clickElement()

#go back
remDr$goBack()

#search for something
search_box <- remDr$findElement(using = "id", "gh-ac")
search_box$sendKeysToElement(list("playstation", key = "enter"))

#scroll to the end of the website
remDr$executeScript("window.scrollTo(0, document.body.scrollHeight);")

#click on the United States filter box
us_checkbox <- remDr$findElement(using = "xpath", '//input[@aria-label="NTSC-U/C (US/Canada)"]')
us_checkbox$clickElement()

#click on the Type dropdown
remDr$findElement(using = "xpath", '//*[text()="Type"]')$clickElement()

type_home_console <- remDr$findElement(using = "xpath", '//input[@aria-label="Home Console"]')$clickElement()

#identify the price
prices <- remDr$findElements(using = "class name", "s-item__price")
length(prices)

price_values <- lapply(prices, function(x) x$getElementText()) %>%
  unlist() %>%
  str_remove_all("[$]") %>%
  str_remove_all("[NT]") %>%
  str_remove_all("[,]")

remove_not_price <- grep("to", price_values)
mean_price_values <- price_values[-remove_not_price] %>%
  as.numeric() %>%
  mean(., na.rm = TRUE)

#terminate the selenium server
system("taskkill /im java.exe /f")
```